apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-example-app
  name: prometheus-example-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        ports:
        - name: http-web
          containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: demo
spec:
  selector:
    app: prometheus-example-app
  ports:
  - name: http-web
    port: 8080
    targetPort: 8080
  type: NodePort

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: prometheus-example-app
    release: prometheus
  name: prometheus-example-app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: prometheus-example-app
  podMetricsEndpoints:
  - port: http-web